# Generated by Django 2.2.4 on 2022-10-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0002_auto_20221019_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='planted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='treeapp.User'),
        ),
    ]
